#! /bin/bash

PASS="123456"

echo "$PASS" | sudo -S add-apt-repository ppa:numix/ppa -y
echo "$PASS" | sudo -S apt update -y
echo "$PASS" | sudo -S apt install -y numix-icon-theme-circle arc-theme

#import config file
. ./switch.conf

#Convert rgba value to 0-255 range
LR="$(($LIGHT_RED/255))"
LG="$(($LIGHT_GREEN/255))"
LB="$(($LIGHT_BLUE/255))"

#xfce4 settings
xfconf-query -c xsettings -p /Net/ThemeName -s "$LIGHT_THEME"

#icon pack
xfconf-query -c xsettings -p /Net/IconThemeName -s "$LIGHT_ICON"

#window manager: if you're using xfcewm
xfconf-query -c xfwm4 -p /general/theme -s "$LIGHT_WM_THEME"

#wallpaper change
xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitor0/workspace0/last-image -s "$LIGHT_WALLPAPER"
